spring:
  redis:
    host: session-redis-001.pxr9ze.0001.apn2.cache.amazonaws.com
    port: 6379
    configuration:
      secure:
        true
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  #  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mariadb://acme.appleluck.com:3306/appleluck
    username: admin
    password: Soldesk!
    driver-class-name: org.mariadb.jdbc.Driver
#  h2:
#    console:
#      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    include: oauth
logging.level:
  org.hibernate.SQL: debug

