apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jenkins
  template:
    metadata:
      labels:
        run: jenkins
    spec:
      containers:
        - image: 256746287291.dkr.ecr.ap-northeast-2.amazonaws.com/jenkins:latest
          name: jenkins
          ports:
            - containerPort: 80